name: Sr Barriga comes around

on:
  schedule:
    - cron: "0 0 1 1 *"

jobs:
  execute:
    env:
      MONGO_URI: ${{secrets.MONGO_URI}}
      SPOTIFY_VALUE: ${{secrets.SPOTIFY_VALUE}} 
      API_TELEGRAM: ${{secrets.API_TELEGRAM}} 
      BOT_KEY: ${{secrets.BOT_KEY}} 
      CHAT_ID: ${{secrets.CHAT_ID}}
    
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies and run app
        run: pip install -r requirements.txt && python app/main.py
